### ISSUE TITLE
AGB Mode appears to be broken...

### ISSUE THREAD

**Issue by ApacheThunder** [roxas75/rxTools#190]
Current build appears to have broken AGB_FIRM. It won't boot and data install screen comes up everytime. Did you change structure of firmware.bin again? If not something broke. It's never creating the agb_firm bin file in the data folder. This breaks AGB mode as well as causing the data install screen to come up everytime rxTools is booted. It does create TWL and Native_Firm bin files correctly, so TWL mode and rxMode still work.

**Comment by dukesrg** [comment]
Maybe #194 should fix that

**Comment by ApacheThunder** [comment]
The initial data install screen appears to work now. (only comes up once). But it still fails to boot into AGB Mode when I try to boot a GBA VC game. (It just black screens. No error is shown)

**Comment by kot2002** [comment]
It seems AGB_FIRM is not patched correctly.
I replaced generated /rxTools/data/0004013800000202.bin with old one (before using elf format?), and now GBA games works.

**Comment by soarqin** [comment]
I added some log to source codes and found that elf patch reads offset incorrectly:
AGB patch correct offset: 0x0009D2A8
current elf patch offset: 0x0008B800

There must be something wrong in elf reading codes, I will look into it later.

**Comment by soarqin** [comment]
found that arm11 things were added to FirmInfo struct but patching info data was not fixed for that.
I tried to insert arm11 fieds into them but patches are still not working. I am going to add more logs to check what was wrong.

**Comment by Syphurith** [comment]
@soarqin Could we do these ARM11 patching now? IIRC the rxTools main part is in ARM9.
~~Two cores is seperated in design and it requires tricks to switch..~~

**Comment by AlbertoSONIC** [comment]
@Syphurith I need the arm11 patches for a special incoming featurea ;)

**Comment by Syphurith** [comment]
@AlbertoSONIC Yes and it could be great feature. Hope you would work on it smoothly.

**Comment by AlbertoSONIC** [comment]
:+1:
